import { JetBrains_Mono } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;

// components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import { Toaster } from "sonner";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.className} antialiased`}
      >
        <Header />
        <StairTransition />
        <Toaster
          position="top-center"
          richColors
          closeButton={true}
          toastOptions={{
            success: {
              duration: 4000,
              style: {
                background: "#22c55e", // green background
                color: "#fff",
              },
            },
            error: {
              duration: 6000,
              style: {
                background: "#ef4444", // red background
                color: "#fff",
              },
            },
          }}
        />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
